package rules

import com.example.shop_user.dto.Order
import com.example.shop_user.dto.RuleResult
import java.math.BigDecimal
import com.example.shop_user.service.UserService;
import com.example.shop_user.entity.User;


global org.slf4j.Logger logger
global UserService userService;

rule "VIP"
    when
        $order: Order(customerType == "VIP", amount > 1000)
    then
        $order.setDiscount(new BigDecimal("0.15"));
        logger.info("执行到VIP");
        insert(new RuleResult("VIP", new BigDecimal("0.15")));
end

rule "NULL_TYPE"
    when
        $order: Order(customerType == null, amount > 1000)
    then
        $order.setDiscount(new BigDecimal("0.15"));
        logger.info("执行到NULL_TYPE");
        $order.setCustomerType("VIP");
        update($order)
        insert(new RuleResult("NULL_TYPE", new BigDecimal("0.2")));
end

rule "Normal"
    when
        $order: Order(customerType == "NORMAL", amount > 500)
    then
        $order.setDiscount(new BigDecimal("0.05"));
        insert(new RuleResult("Normal", new BigDecimal("0.05")));
end

rule "Normal"
    when
        $order: Order(customerType == "NORMAL", amount > 500)
        $user:User(this == userService.get($order.userId)) from userService.get($order.userId)
    then
        $order.setDiscount(new BigDecimal("0.05"));
        insert(new RuleResult("Normal", new BigDecimal("0.05")));
end

query "DiscountResults"
    $result: RuleResult()
end